### ISSUE TITLE
[Request] [@FASearchBot] Adding option to show title for results to subscribed query

### ISSUE THREAD

**Issue by ZarosTenjin** [Deer-Spangle/FA-search-bot#14]
This is based on @FASearchBot:
Currently if a result for a subscribed query is displayed by the bot it shows the submission itself with a direct link to the results FA page and in case of stories it also adds a direct download link. However especially with story content a lot of the time no thumbnail is uploaded for the content. It would be very helpful if maybe the title and creator would be listed with the telegram message to better identify the work. This would be especially helpful in the usecase of enjoying or heavily disliking a creator and then being able to quickly add them to the subscriptions/blacklist via the artist:-tag.

![shot-2021-05-17_16-17-00](https://user-images.githubusercontent.com/17838944/118504295-ab478580-b72b-11eb-8dd1-f41d814f0489.jpg)

**Comment by Deer-Spangle** [comment]
That does seem a smart idea!
I was considering something like that for subscriptions in general, but having for the stories and such that lack thumbnails does seem handy

**Comment by Deer-Spangle** [comment]
> having for the stories and such that lack thumbnails does seem handy

I just realised this morning, after working on this a chunk last night, (writing stuff to detect default thumbnail and stuff), that this probably just a good idea for all stories and music, whether or not they have a preview pic, the bot should put the title and author in the caption by default.
Darn.
That should be easier than I planned then!

**Comment by ZarosTenjin** [comment]
Maybe even have it as a /command-toggle for all submission types? The ability to display title and artist that is. that way its easier to find the piece on FA if you see a piece of artwork you really like from your searches.

**Comment by Deer-Spangle** [comment]
> Maybe even have it as a /command-toggle for all submission types? The ability to display title and artist that is. that way its easier to find the piece on FA if you see a piece of artwork you really like from your searches.

Yess, I do want to do that in the future

But for now, I've added title and author for stories and music, that's all deployed now, thank you for the suggestion! ^_^
